name: Test

on:
  push:

jobs:
  job:
    name: Job1
    runs-on: self-hosted

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Action
        uses: ./
        with:
          log_file: "build.log"
          compile_commands: "compile_commands.json"
          config: "config"