name: Test

on:
  pull_request:
    branches:
      - "main"
    paths: 
      - "src/main.py"
      - ".github/workflows/test.yml"

jobs:
  job:
    name: Job1
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Action
        uses: ./
        with:
          log_file: "build.log"
          compile_commands: "compile_commands.json"
          config: "config"
